# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
        exclude: "mkdocs.yml"
    -   id: check-added-large-files
        args: ['--maxkb=1000']
        exclude: "notebooks"
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-aws-credentials
    -   id: detect-private-key
-   repo: https://github.com/asottile/pyupgrade  # update python syntax
    rev: v2.37.3
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
- repo: local
  hooks:
    - id: test
      name: test
      entry: bash -c "cd App && make"
      args: ["test"]
      language: system
      pass_filenames: false
    - id: clean
      name: clean
      entry: bash -c "cd App && make"
      args: ["clean"]
      language: system
      pass_filenames: false
    - id: dvc
      name: dvc
      entry: bash -c "cd App && make"
      args: ["dvc"]
      language: system
      pass_filenames: false