# mkdocs.yml
site_name: MLOps course tagifai
site_url: https://madewithml.com/
repo_url: https://github.com/MerlinSchaefer/MLOps_course_mwml
nav:
  - Home: index.md
  - workflows:
    - main: tagifai/main.md
  - tagifai:
    - data: tagifai/data.md
    - evaluate: tagifai/evaluate.md
    - predict: tagifai/predict.md
    - train: tagifai/train.md
  - utils: utils.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .  # reload docs for any file changes

